# Generated by Django 5.0.4 on 2024-04-28 15:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_productgallery"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productgallery",
            options={
                "verbose_name": "productgallery",
                "verbose_name_plural": "product gallery",
            },
        ),
    ]
